<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" ignored="0" total="8" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="FREE CRM Application Test Automation Test Suite" duration-ms="63646" started-at="2019-09-06T01:59:18Z" finished-at="2019-09-06T02:00:21Z">
    <groups>
    </groups>
    <test name="Free CRM App Test Cases" duration-ms="63646" started-at="2019-09-06T01:59:18Z" finished-at="2019-09-06T02:00:21Z">
      <class name="com.qa.testcases.HomePageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.testcases.HomePageTest@64616ca2]" name="setUp" is-config="true" duration-ms="6537" started-at="2019-09-05T21:59:18Z" finished-at="2019-09-05T21:59:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="elementPresentTest()[pri:1, instance:com.qa.testcases.HomePageTest@64616ca2]" name="elementPresentTest" duration-ms="213" started-at="2019-09-05T21:59:24Z" finished-at="2019-09-05T21:59:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com.qa.testcases.HomePageTest.elementPresentTest(HomePageTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- elementPresentTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.testcases.HomePageTest@64616ca2]" name="tearDown" is-config="true" duration-ms="939" started-at="2019-09-05T21:59:25Z" finished-at="2019-09-05T21:59:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.testcases.HomePageTest@64616ca2]" name="setUp" is-config="true" duration-ms="4065" started-at="2019-09-05T21:59:25Z" finished-at="2019-09-05T21:59:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="elementPresentTest()[pri:1, instance:com.qa.testcases.HomePageTest@64616ca2]" name="elementPresentTest" duration-ms="131" started-at="2019-09-05T21:59:30Z" finished-at="2019-09-05T21:59:30Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com.qa.testcases.HomePageTest.elementPresentTest(HomePageTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- elementPresentTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.testcases.HomePageTest@64616ca2]" name="tearDown" is-config="true" duration-ms="860" started-at="2019-09-05T21:59:30Z" finished-at="2019-09-05T21:59:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.testcases.HomePageTest@64616ca2]" name="setUp" is-config="true" duration-ms="3681" started-at="2019-09-05T21:59:31Z" finished-at="2019-09-05T21:59:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="elementPresentTest()[pri:1, instance:com.qa.testcases.HomePageTest@64616ca2]" name="elementPresentTest" duration-ms="180" started-at="2019-09-05T21:59:34Z" finished-at="2019-09-05T21:59:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com.qa.testcases.HomePageTest.elementPresentTest(HomePageTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- elementPresentTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.testcases.HomePageTest@64616ca2]" name="tearDown" is-config="true" duration-ms="826" started-at="2019-09-05T21:59:34Z" finished-at="2019-09-05T21:59:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.testcases.HomePageTest@64616ca2]" name="setUp" is-config="true" duration-ms="3816" started-at="2019-09-05T21:59:35Z" finished-at="2019-09-05T21:59:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="elementPresentTest()[pri:1, instance:com.qa.testcases.HomePageTest@64616ca2]" name="elementPresentTest" duration-ms="152" started-at="2019-09-05T21:59:39Z" finished-at="2019-09-05T21:59:39Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com.qa.testcases.HomePageTest.elementPresentTest(HomePageTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- elementPresentTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.testcases.HomePageTest@64616ca2]" name="tearDown" is-config="true" duration-ms="1056" started-at="2019-09-05T21:59:39Z" finished-at="2019-09-05T21:59:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.testcases.HomePageTest@64616ca2]" name="setUp" is-config="true" duration-ms="3881" started-at="2019-09-05T21:59:40Z" finished-at="2019-09-05T21:59:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="emptyQueryCheck()[pri:2, instance:com.qa.testcases.HomePageTest@64616ca2]" name="emptyQueryCheck" duration-ms="262" started-at="2019-09-05T21:59:44Z" finished-at="2019-09-05T21:59:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emptyQueryCheck -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.testcases.HomePageTest@64616ca2]" name="tearDown" is-config="true" duration-ms="972" started-at="2019-09-05T21:59:44Z" finished-at="2019-09-05T21:59:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.testcases.HomePageTest@64616ca2]" name="setUp" is-config="true" duration-ms="3914" started-at="2019-09-05T21:59:45Z" finished-at="2019-09-05T21:59:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="searchPositiveResultCount()[pri:3, instance:com.qa.testcases.HomePageTest@64616ca2]" name="searchPositiveResultCount" duration-ms="386" started-at="2019-09-05T21:59:49Z" finished-at="2019-09-05T21:59:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchPositiveResultCount -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.testcases.HomePageTest@64616ca2]" name="tearDown" is-config="true" duration-ms="833" started-at="2019-09-05T21:59:50Z" finished-at="2019-09-05T21:59:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.testcases.HomePageTest@64616ca2]" name="setUp" is-config="true" duration-ms="4128" started-at="2019-09-05T21:59:50Z" finished-at="2019-09-05T21:59:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="searchNoResultCount()[pri:4, instance:com.qa.testcases.HomePageTest@64616ca2]" name="searchNoResultCount" duration-ms="20381" started-at="2019-09-05T21:59:55Z" finished-at="2019-09-05T22:00:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchNoResultCount -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.testcases.HomePageTest@64616ca2]" name="tearDown" is-config="true" duration-ms="1105" started-at="2019-09-05T22:00:15Z" finished-at="2019-09-05T22:00:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.testcases.HomePageTest@64616ca2]" name="setUp" is-config="true" duration-ms="4007" started-at="2019-09-05T22:00:16Z" finished-at="2019-09-05T22:00:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="matchSearchResultQuery()[pri:5, instance:com.qa.testcases.HomePageTest@64616ca2]" name="matchSearchResultQuery" duration-ms="411" started-at="2019-09-05T22:00:20Z" finished-at="2019-09-05T22:00:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- matchSearchResultQuery -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.testcases.HomePageTest@64616ca2]" name="tearDown" is-config="true" duration-ms="826" started-at="2019-09-05T22:00:21Z" finished-at="2019-09-05T22:00:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.testcases.HomePageTest -->
    </test> <!-- Free CRM App Test Cases -->
  </suite> <!-- FREE CRM Application Test Automation Test Suite -->
</testng-results>
