<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="Shadli-PC" name="com.qa.testcases.HomePageTest" tests="8" failures="1" timestamp="06 Sep 2019 02:00:23 GMT" time="63.562" errors="0">
  <testcase name="elementPresentTest" time="5.046" classname="com.qa.testcases.HomePageTest">
    <skipped/>
  </testcase> <!-- elementPresentTest -->
  <testcase name="elementPresentTest" time="4.954" classname="com.qa.testcases.HomePageTest">
    <skipped/>
  </testcase> <!-- elementPresentTest -->
  <testcase name="elementPresentTest" time="5.052" classname="com.qa.testcases.HomePageTest">
    <skipped/>
  </testcase> <!-- elementPresentTest -->
  <testcase name="elementPresentTest" time="5.106" classname="com.qa.testcases.HomePageTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com.qa.testcases.HomePageTest.elementPresentTest(HomePageTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
    </failure>
  </testcase> <!-- elementPresentTest -->
  <testcase name="emptyQueryCheck" time="5.383" classname="com.qa.testcases.HomePageTest"/>
  <testcase name="searchPositiveResultCount" time="7.862" classname="com.qa.testcases.HomePageTest"/>
  <testcase name="searchNoResultCount" time="25.034" classname="com.qa.testcases.HomePageTest"/>
  <testcase name="matchSearchResultQuery" time="5.125" classname="com.qa.testcases.HomePageTest"/>
</testsuite> <!-- com.qa.testcases.HomePageTest -->
